"""session_exp

Revision ID: 0c1e883f7f7c
Revises: b45fc96171b7
Create Date: 2023-07-22 14:42:04.229941

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c1e883f7f7c"
down_revision = "b45fc96171b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("session_exp", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "session_exp")
    # ### end Alembic commands ###
