"""session_access_token

Revision ID: 83ac4486af09
Revises: 6098106e1c8a
Create Date: 2023-07-17 11:45:59.031170

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "83ac4486af09"
down_revision = "6098106e1c8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("access_token", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "access_token")
    # ### end Alembic commands ###
