"""fk_on_delete

Revision ID: b45fc96171b7
Revises: aab9f2f39b08
Create Date: 2023-07-20 13:21:00.433796

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b45fc96171b7"
down_revision = "aab9f2f39b08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sessions_user_id_fkey", "sessions", type_="foreignkey")
    op.create_foreign_key(
        None, "sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("user_roles_role_id_fkey", "user_roles", type_="foreignkey")
    op.drop_constraint("user_roles_user_id_fkey", "user_roles", type_="foreignkey")
    op.create_foreign_key(
        None, "user_roles", "roles", ["role_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user_roles", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.create_foreign_key(
        "user_roles_user_id_fkey", "user_roles", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "user_roles_role_id_fkey", "user_roles", "roles", ["role_id"], ["id"]
    )
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key(
        "sessions_user_id_fkey", "sessions", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
